"use client";
import{useEffect,useMemo,useState}from"react";
type T={name:string;short?:string;logo?:string};type F={round:number;date?:string;time?:string;home:string;away:string;played:boolean;homeScore:number|null;awayScore:number|null};
const colors:Record<string,string>={"FK Vchynice / TJ Slavoj Sulejovice":"#f8dc30","Dynamo Podlusky":"#019341","ASK Lovosice":"#31428b","SK Velemín":"#009fe0","TJ Viktoria Budyně nad Ohří":"#180b8e","TJ Sokol Černiv":"#297b40","SK Sokol Malé Žernoseky":"#b92c2b","Městský Sportovní klub Třebenice":"#17854e","SK Sokol Brozany":"#c62223"};
const slugs:Record<string,string>={"TJ Viktoria Budyně nad Ohří":"budyne","TJ Sokol Černiv":"cerniv","FK Vchynice / TJ Slavoj Sulejovice":"vchynice-sulejovice","SK Sokol Brozany":"brozany","SK Velemín":"velemin","SK Sokol Malé Žernoseky":"male-zernoseky","Městský Sportovní klub Třebenice":"trebenice","Dynamo Podlusky":"podlusky","ASK Lovosice":"lovosice"};
const months=["leden","únor","březen","duben","květen","červen","červenec","srpen","září","říjen","listopad","prosinec"],pad=(n:number)=>String(n).padStart(2,"0");
const CalendarIcon=()=> <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 2v3M17 2v3M3.5 9h17M5.5 4h13a2 2 0 0 1 2 2v13a2 2 0 0 1-2 2h-13a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Z"/><path d="M7 12h2v2H7zM11 12h2v2h-2zM15 12h2v2h-2zM7 16h2v2H7zM11 16h2v2h-2z"/></svg>;
const AppleIcon=()=> <svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M17.05 12.54c.02-2.03 1.66-3 1.74-3.05-.95-1.39-2.43-1.58-2.95-1.6-1.24-.13-2.45.74-3.08.74-.64 0-1.6-.73-2.64-.71-1.34.02-2.6.8-3.29 2.01-1.43 2.47-.36 6.11 1.01 8.11.69.98 1.49 2.07 2.53 2.03 1.02-.04 1.4-.65 2.63-.65 1.22 0 1.58.65 2.65.63 1.09-.02 1.78-.98 2.44-1.97.79-1.13 1.11-2.25 1.12-2.31-.03-.01-2.14-.83-2.16-3.23ZM15.03 6.58c.55-.69.93-1.62.82-2.58-.8.04-1.81.56-2.38 1.23-.51.59-.96 1.56-.84 2.48.91.07 1.83-.46 2.4-1.13Z"/></svg>;
const GoogleIcon=()=> <svg viewBox="0 0 24 24" aria-hidden="true"><path fill="#4285F4" d="M21.6 12.23c0-.71-.06-1.24-.2-1.79H12v3.4h5.52a4.72 4.72 0 0 1-2.05 3.1l2.98 2.31c1.93-1.78 2.96-4.4 2.96-7.15Z"/><path fill="#34A853" d="M12 22c2.7 0 4.96-.89 6.61-2.42l-3.17-2.45c-.85.58-1.99.99-3.44.99-2.6 0-4.8-1.76-5.59-4.19l-3.24 2.51A10 10 0 0 0 12 22Z"/><path fill="#FBBC05" d="M6.41 13.93A6 6 0 0 1 6.08 12c0-.67.12-1.32.32-1.93L3.17 7.56A10 10 0 0 0 2 12c0 1.6.38 3.11 1.17 4.44l3.24-2.51Z"/><path fill="#EA4335" d="M12 5.88c1.88 0 3.15.81 3.88 1.49l2.8-2.74C16.96 3.03 14.7 2 12 2a10 10 0 0 0-8.83 5.56l3.23 2.51C7.2 7.64 9.4 5.88 12 5.88Z"/></svg>;
export default function ClubTheme({teams,fixtures}:{teams:T[];fixtures:F[]}){const[selected,setSelected]=useState<string|null>(null),[open,setOpen]=useState(false),[mine,setMine]=useState(false),[calendarOpen,setCalendarOpen]=useState(false),[monthOffset,setMonthOffset]=useState(0);
const mark=(name:string,onlyMine:boolean)=>{const root=document.documentElement;root.style.setProperty("--club",colors[name]||"#111827");root.dataset.club=name;document.querySelectorAll<HTMLElement>(".match[data-home][data-away]").forEach(el=>{const yes=el.dataset.home===name||el.dataset.away===name;el.classList.toggle("favoriteMatch",yes);el.classList.toggle("hiddenByTeamFilter",onlyMine&&!yes)});setSelected(name);setMine(onlyMine)};
useEffect(()=>{const s=localStorage.getItem("favoriteTeam"),m=localStorage.getItem("onlyFavoriteMatches")==="1";if(s&&colors[s])mark(s,m);else setOpen(true)},[]);const choose=(name:string)=>{localStorage.setItem("favoriteTeam",name);mark(name,mine);setOpen(false);setMonthOffset(0)};const toggleMine=()=>{if(!selected)return;const n=!mine;localStorage.setItem("onlyFavoriteMatches",n?"1":"0");mark(selected,n)};const t=teams.find(x=>x.name===selected);
const myGames=useMemo(()=>selected?fixtures.filter(f=>f.home===selected||f.away===selected).filter(f=>f.date).sort((a,b)=>(a.date||"").localeCompare(b.date||"")):[],[selected,fixtures]);const next=myGames.find(g=>!g.played),played=myGames.filter(g=>g.played),last=played.at(-1);const form=played.slice(-5).map(g=>{if(g.homeScore===g.awayScore)return"D";const win=(g.home===selected&&g.homeScore!>g.awayScore!)||(g.away===selected&&g.awayScore!>g.homeScore!);return win?"W":"L"});
const table=useMemo(()=>teams.map(team=>{let pts=0,gd=0,p=0;fixtures.filter(f=>f.played&&(f.home===team.name||f.away===team.name)&&f.homeScore!==null&&f.awayScore!==null).forEach(f=>{p++;const gf=f.home===team.name?f.homeScore!:f.awayScore!,ga=f.home===team.name?f.awayScore!:f.homeScore!;gd+=gf-ga;pts+=gf>ga?3:gf===ga?1:0});return{name:team.name,pts,gd,p}}).sort((a,b)=>b.pts-a.pts||b.gd-a.gd),[teams,fixtures]);const pos=selected?table.findIndex(x=>x.name===selected)+1:0;
const base=useMemo(()=>{const future=next?.date||myGames[0]?.date||"2026-10-01";const[y,m]=future.split("-").map(Number);return new Date(y,m-1+monthOffset,1)},[myGames,next,monthOffset]);const year=base.getFullYear(),month=base.getMonth(),days=new Date(year,month+1,0).getDate(),start=(new Date(year,month,1).getDay()+6)%7;const gameDays=new Set(myGames.filter(g=>g.date?.startsWith(`${year}-${pad(month+1)}`)).map(g=>Number(g.date?.slice(8,10))));const slug=selected?slugs[selected]:null,webcalUrl=slug?`webcal://goluj.cz/api/calendar/${slug}`:"",googleUrl=webcalUrl?`https://calendar.google.com/calendar/r?cid=${encodeURIComponent(webcalUrl)}`:"";const logo=(n:string)=>teams.find(x=>x.name===n)?.logo||"";
return <><div className="clubControls"><label className="teamFilter"><span>Zobrazit jen můj tým</span><button type="button" role="switch" aria-checked={mine} className={"switch "+(mine?"active":"")} onClick={toggleMine}><i/></button></label><button className="changeClub" onClick={()=>setOpen(true)}>{t?.logo&&<img src={t.logo} alt=""/>}</button></div>
{selected&&t&&<section className="myTeamHub"><div className="hubTop"><div className="hubIdentity"><img src={t.logo||""} alt=""/><div><small>MŮJ TÝM</small><strong>{selected}</strong></div></div><a className="hubTeamLink" href={`/tym/${slug}`}>Detail týmu →</a></div><div className="hubMain"><div className="nextMatch"><span className="hubEyebrow">PŘÍŠTÍ ZÁPAS</span>{next?<><div className="nextTeams"><div className="nextClub"><img src={logo(next.home)} alt=""/><strong>{next.home}</strong></div><span className="nextVs">VS</span><div className="nextClub"><strong>{next.away}</strong><img src={logo(next.away)} alt=""/></div></div><div className="nextWhen"><span>{next.date?new Intl.DateTimeFormat("cs-CZ",{weekday:"short",day:"numeric",month:"long"}).format(new Date(next.date+"T12:00:00")):""} · {next.time}</span><b>{next.round}. KOLO</b></div></>:<strong>Program dokončen</strong>}</div><div className="hubStat"><span className="hubEyebrow">TABULKA</span><strong>{pos}.</strong><span>{table.find(x=>x.name===selected)?.pts||0} bodů</span></div><div className="hubStat"><span className="hubEyebrow">FORMA</span><div className="formDots">{form.length?form.map((x,i)=><i key={i} className={x.toLowerCase()}>{x==="W"?"V":x==="D"?"R":"P"}</i>):<span>—</span>}</div>{last&&<span>naposledy {last.homeScore}:{last.awayScore}</span>}</div></div></section>}
{selected&&<><button className="calendarTab" onClick={()=>setCalendarOpen(true)}><span className="calendarIcon"><CalendarIcon/></span><b>Kalendář</b></button>{calendarOpen&&<><div className="calendarShade" onClick={()=>setCalendarOpen(false)}/><aside className="calendarDrawer"><button className="calendarClose" onClick={()=>setCalendarOpen(false)}>×</button><div className="calendarTeam">{t?.logo&&<img src={t.logo} alt=""/>}<div><small>MŮJ TÝM</small><strong>{selected}</strong></div></div><div className="calendarNav"><button onClick={()=>setMonthOffset(x=>x-1)}>‹</button><b>{months[month]} {year}</b><button onClick={()=>setMonthOffset(x=>x+1)}>›</button></div><div className="miniCalendar"><div>PO</div><div>ÚT</div><div>ST</div><div>ČT</div><div>PÁ</div><div>SO</div><div>NE</div>{Array.from({length:start}).map((_,i)=><span key={"e"+i}/>)}{Array.from({length:days},(_,i)=>i+1).map(d=><span className={gameDays.has(d)?"hasGame":""} key={d}>{d}</span>)}</div><div className="calendarGames"><small>ZÁPASY V MĚSÍCI</small>{myGames.filter(g=>g.date?.startsWith(`${year}-${pad(month+1)}`)).map((g,i)=><div className="calendarGame" key={i}><b>{Number(g.date?.slice(8,10))}.</b><span><strong>{g.home===selected?g.away:g.home}</strong><small>{g.home===selected?"DOMÁCÍ HŘIŠTĚ":"HŘIŠTĚ SOUPEŘE"} · {g.time||"—"}</small></span></div>)}</div><div className="calendarSubscriptions">{googleUrl&&<a className="calendarProvider googleProvider" href={googleUrl} target="_blank"><span className="providerIcon"><GoogleIcon/></span><span><small>GOOGLE</small><strong>Přidat do kalendáře</strong></span></a>}{webcalUrl&&<a className="calendarProvider appleProvider" href={webcalUrl}><span className="providerIcon"><AppleIcon/></span><span><small>APPLE</small><strong>Přidat do kalendáře</strong></span></a>}</div><p className="calendarHint">Kalendář se průběžně aktualizuje podle termínů na Góluj.cz.</p></aside></>}</>}
{open&&<div className="clubModalBackdrop"><div className="clubModal"><div className="clubModalHead"><span>MOJE BARVY</span><h2>Vyberte si svůj tým</h2><p>Tabulka i zápasy se přizpůsobí barvám vašeho klubu.</p></div><div className="clubGrid">{teams.map(x=><button key={x.name} onClick={()=>choose(x.name)} style={{"--pick":colors[x.name]} as React.CSSProperties}>{x.logo&&<img src={x.logo} alt=""/>}<strong>{x.name}</strong></button>)}</div>{selected&&<button className="modalClose" onClick={()=>setOpen(false)}>Zavřít</button>}</div></div>}</>}
