"use client";
import{useEffect,useMemo,useState}from"react";

type T={name:string;short?:string;logo?:string};
type F={round:number;date?:string;time?:string;home:string;away:string;played:boolean};
const colors:Record<string,string>={"FK Vchynice / TJ Slavoj Sulejovice":"#f8dc30","Dynamo Podlusky":"#019341","ASK Lovosice":"#31428b","SK Velemín":"#009fe0","TJ Viktoria Budyně nad Ohří":"#180b8e","TJ Sokol Černiv":"#297b40","SK Sokol Malé Žernoseky":"#b92c2b","Městský Sportovní klub Třebenice":"#17854e","SK Sokol Brozany":"#c62223"};
const slugs:Record<string,string>={"TJ Viktoria Budyně nad Ohří":"budyne","TJ Sokol Černiv":"cerniv","FK Vchynice / TJ Slavoj Sulejovice":"vchynice-sulejovice","SK Sokol Brozany":"brozany","SK Velemín":"velemin","SK Sokol Malé Žernoseky":"male-zernoseky","Městský Sportovní klub Třebenice":"trebenice","Dynamo Podlusky":"podlusky","ASK Lovosice":"lovosice"};
const months=["leden","únor","březen","duben","květen","červen","červenec","srpen","září","říjen","listopad","prosinec"];
const pad=(n:number)=>String(n).padStart(2,"0");
const CalendarIcon=()=> <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 2v3M17 2v3M3.5 9h17M5.5 4h13a2 2 0 0 1 2 2v13a2 2 0 0 1-2 2h-13a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Z"/><path d="M7 12h2v2H7zM11 12h2v2h-2zM15 12h2v2h-2zM7 16h2v2H7zM11 16h2v2h-2z"/></svg>;
export default function ClubTheme({teams,fixtures}:{teams:T[];fixtures:F[]}){
 const[selected,setSelected]=useState<string|null>(null),[open,setOpen]=useState(false),[mine,setMine]=useState(false),[calendarOpen,setCalendarOpen]=useState(false),[monthOffset,setMonthOffset]=useState(0);
 const mark=(name:string,onlyMine:boolean)=>{const c=colors[name]||"#111827",root=document.documentElement;root.style.setProperty("--club",c);root.dataset.club=name;root.classList.toggle("onlyMine",onlyMine);document.querySelectorAll<HTMLElement>(".match[data-home][data-away]").forEach(el=>{const isMine=el.dataset.home===name||el.dataset.away===name;el.classList.toggle("favoriteMatch",isMine);el.classList.toggle("hiddenByTeamFilter",onlyMine&&!isMine)});document.querySelectorAll<HTMLDetailsElement>(".matchAccordion").forEach(d=>{const n=d.querySelectorAll(".match:not(.hiddenByTeamFilter)").length,badge=d.querySelector<HTMLElement>(".accCount");if(badge)badge.textContent=String(n)});setSelected(name);setMine(onlyMine)};
 useEffect(()=>{const s=localStorage.getItem("favoriteTeam"),m=localStorage.getItem("onlyFavoriteMatches")==="1";if(s&&colors[s])mark(s,m);else setOpen(true);const ds=[...document.querySelectorAll<HTMLDetailsElement>(".matchAccordion")];const onToggle=(e:Event)=>{const cur=e.currentTarget as HTMLDetailsElement;if(cur.open)ds.forEach(d=>{if(d!==cur)d.open=false})};ds.forEach(d=>d.addEventListener("toggle",onToggle));return()=>ds.forEach(d=>d.removeEventListener("toggle",onToggle))},[]);
 const choose=(name:string)=>{localStorage.setItem("favoriteTeam",name);mark(name,mine);setOpen(false);setMonthOffset(0)};const toggleMine=()=>{if(!selected)return;const n=!mine;localStorage.setItem("onlyFavoriteMatches",n?"1":"0");mark(selected,n)};const t=teams.find(x=>x.name===selected);
 const myGames=useMemo(()=>selected?fixtures.filter(f=>f.home===selected||f.away===selected).filter(f=>f.date).sort((a,b)=>(a.date||"").localeCompare(b.date||"")):[],[selected,fixtures]);
 const base=useMemo(()=>{const future=myGames.find(g=>!g.played)?.date||myGames[0]?.date||"2026-10-01";const[y,m]=future.split("-").map(Number);return new Date(y,m-1+monthOffset,1)},[myGames,monthOffset]);
 const year=base.getFullYear(),month=base.getMonth(),days=new Date(year,month+1,0).getDate(),start=(new Date(year,month,1).getDay()+6)%7;const gameDays=new Set(myGames.filter(g=>{const d=new Date((g.date||"")+"T12:00:00");return d.getFullYear()===year&&d.getMonth()===month}).map(g=>Number(g.date?.slice(8,10))));
 const slug=selected?slugs[selected]:null;const feedUrl=slug?`https://goluj.cz/api/calendar/${slug}`:"";const webcalUrl=slug?`webcal://goluj.cz/api/calendar/${slug}`:"";const googleUrl=webcalUrl?`https://calendar.google.com/calendar/r?cid=${encodeURIComponent(webcalUrl)}`:"";
 return <><div className="clubControls"><label className="teamFilter"><span>Zobrazit jen můj tým</span><button type="button" role="switch" aria-checked={mine} className={"switch "+(mine?"active":"")} onClick={toggleMine} disabled={!selected}><i/></button></label><button className="changeClub" onClick={()=>setOpen(true)}>{t?.logo&&<img src={t.logo} alt=""/>}<span>{t?"Změnit tým":"Vybrat tým"}</span></button></div>
 {selected&&<><button className="calendarTab" onClick={()=>setCalendarOpen(true)} aria-label="Otevřít kalendář týmu"><span className="calendarIcon"><CalendarIcon/></span><b>Kalendář</b></button>{calendarOpen&&<><div className="calendarShade" onClick={()=>setCalendarOpen(false)}/><aside className="calendarDrawer"><button className="calendarClose" onClick={()=>setCalendarOpen(false)} aria-label="Zavřít">×</button><div className="calendarTeam">{t?.logo&&<img src={t.logo} alt=""/>}<div><small>MŮJ TÝM</small><strong>{selected}</strong></div></div><div className="calendarNav"><button onClick={()=>setMonthOffset(x=>x-1)}>‹</button><b>{months[month]} {year}</b><button onClick={()=>setMonthOffset(x=>x+1)}>›</button></div><div className="miniCalendar"><div>PO</div><div>ÚT</div><div>ST</div><div>ČT</div><div>PÁ</div><div>SO</div><div>NE</div>{Array.from({length:start}).map((_,i)=><span key={"e"+i}/>)}{Array.from({length:days},(_,i)=>i+1).map(d=><span className={gameDays.has(d)?"hasGame":""} key={d}>{d}</span>)}</div><div className="calendarGames"><small>ZÁPASY V MĚSÍCI</small>{myGames.filter(g=>g.date?.startsWith(`${year}-${pad(month+1)}`)).map((g,i)=><div className="calendarGame" key={i}><b>{Number(g.date?.slice(8,10))}.</b><span><strong>{g.home===selected?g.away:g.home}</strong><small>{g.home===selected?"DOMÁCÍ HŘIŠTĚ":"HŘIŠTĚ SOUPEŘE"} · {g.time||"—"}</small></span></div>)}</div>{webcalUrl&&<a className="addCalendar" href={webcalUrl}><span className="addPlus">+</span> Odebírat v Apple Kalendáři</a>}{googleUrl&&<a className="googleCalendar" href={googleUrl} target="_blank" rel="noopener noreferrer">Přidat do Google Kalendáře</a>}<p className="calendarHint">Odebíraný kalendář se průběžně aktualizuje podle termínů na Góluj.cz.</p></aside></>}</>}
 {open&&<div className="clubModalBackdrop"><div className="clubModal"><div className="clubModalHead"><span>MOJE BARVY</span><h2>Vyberte si svůj tým</h2><p>Tabulka i zápasy se přizpůsobí barvám vašeho klubu.</p></div><div className="clubGrid">{teams.map(x=><button key={x.name} onClick={()=>choose(x.name)} style={{"--pick":colors[x.name]} as React.CSSProperties}>{x.logo&&<img src={x.logo} alt=""/>}<strong>{x.name}</strong></button>)}</div>{selected&&<button className="modalClose" onClick={()=>setOpen(false)}>Zavřít</button>}</div></div>}</>;
}