import ClubTheme from"./ClubTheme";import SiteFooter from"./SiteFooter";import{calculateStandings}from"../lib/standings";import{competition,fixtures,teams}from"../lib/data";import{getCompetitionFeed}from"../lib/providers/fotbal-cz";
export const revalidate=1800;
const team=(n:string)=>teams.find(t=>t.name===n);
const date=(d?:string)=>d?new Intl.DateTimeFormat("cs-CZ",{day:"numeric",month:"numeric"}).format(new Date(d+"T12:00:00")):"";
export default async function Home(){const feed=await getCompetitionFeed();const liveFixtures=feed.matches as typeof fixtures;const rows=calculateStandings(teams,liveFixtures);const results=liveFixtures.filter(x=>x.played).sort((a,b)=>(b.date||"").localeCompare(a.date||""));const upcoming=liveFixtures.filter(x=>!x.played).sort((a,b)=>(a.date||"9999").localeCompare(b.date||"9999"));return <main>
<ClubTheme teams={teams}/><header className="siteHeader"><div className="siteHeaderInner"><img className="siteLogo" src="/logos/logo.svg" alt="Góluj.cz" /><div className="siteCompetition"><div className="simpleMeta">2026/27 <span className="themeDot">·</span> MLADŠÍ PŘÍPRAVKA</div><h1>2. liga <span>· skupina B</span></h1></div></div></header>
<section className="card"><div className="bar"><strong>Tabulka · všech 9 týmů</strong><span>{feed.source==="fotbal.cz-browser"?"Automaticky z is.fotbal.cz":"Ověřená data"}</span></div><div className="scroll"><table><thead><tr><th>#</th><th className="team">Tým</th><th>Z</th><th>V</th><th>R</th><th>P</th><th>Skóre</th><th>+/-</th><th>B</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.name} className="teamRow" data-team={r.name}><td><b className="rank">{i+1}</b></td><td className="team"><div className="club">{r.logo&&<img src={r.logo} width="40" height="40" alt="" className="logo"/>}<strong>{r.short||r.name}</strong></div></td><td>{r.p}</td><td>{r.w}</td><td>{r.d}</td><td>{r.l}</td><td>{r.gf}:{r.ga}</td><td>{r.gd>0?"+":""}{r.gd}</td><td><b>{r.pts}</b></td></tr>)}</tbody></table></div></section>
<section className="accordions">
<details className="matchAccordion"><summary><div><span className="accEyebrow">ODEHRANÉ</span><strong>Výsledky</strong></div><div className="accRight"><b className="accCount">{results.length}</b><i className="chevron" aria-hidden="true"/></div></summary><div className="accordionBody"><div className="matchList">{results.map((m,i)=><article className="match" data-home={m.home} data-away={m.away} key={"r"+i}><div className="matchMeta"><b>{m.round}. kolo</b><span>{date(m.date)} {m.time}</span></div><div className="side"><img src={team(m.home)?.logo||""} alt=""/><strong>{team(m.home)?.short||m.home}</strong></div><div className="score">{m.homeScore}<i>:</i>{m.awayScore}</div><div className="side away"><strong>{team(m.away)?.short||m.away}</strong><img src={team(m.away)?.logo||""} alt=""/></div></article>)}</div></div></details>
<details className="matchAccordion"><summary><div><span className="accEyebrow">PROGRAM</span><strong>Nadcházející zápasy</strong></div><div className="accRight"><b className="accCount">{upcoming.length}</b><i className="chevron" aria-hidden="true"/></div></summary><div className="accordionBody"><div className="matchList">{upcoming.map((m,i)=><article className="match" data-home={m.home} data-away={m.away} key={"u"+i}><div className="matchMeta"><b>{m.round}. kolo</b><span>{date(m.date)} {m.time}</span></div><div className="side"><img src={team(m.home)?.logo||""} alt=""/><strong>{team(m.home)?.short||m.home}</strong></div><div className="versus">VS</div><div className="side away"><strong>{team(m.away)?.short||m.away}</strong><img src={team(m.away)?.logo||""} alt=""/></div></article>)}</div></div></details>
</section>
<SiteFooter/></main>}